[tasks.build]
install_crate = "wasm-bindgen"
command = "wasm-pack"
args = ["build", "--target", "web"]


[tasks.run]
command = "cargo"
args = ["run", "--release","--bin","webserwer"]
dependencies = ["build"]

